# List of all binary files in the CRTM
# If any files do not end with a .bin or .nc* suffix please also update 
# .gitignore so they do not accidentally get added to the repository
list(APPEND gsi_binaries
  aatsr_envisat.SpcCoeff.bin
  aatsr_envisat.TauCoeff.bin
  abi-81K_g17.SpcCoeff.bin
  abi-81K_g17.TauCoeff.bin
  abi_g16.SpcCoeff.bin
  abi_g16.TauCoeff.bin
  abi_g17.SpcCoeff.bin
  abi_g17.TauCoeff.bin
  abi_g18.SpcCoeff.bin
  abi_g18.TauCoeff.bin
  abi_g19.SpcCoeff.bin
  abi_g19.TauCoeff.bin
  abi_gr.SpcCoeff.bin
  abi_gr.TauCoeff.bin
  AerosolCoeff.bin
  AerosolCoeff.CMAQ.bin
  AerosolCoeff.CMAQ.nc4
  AerosolCoeff.GOCART-GEOS5.bin
  AerosolCoeff.NAAPS.bin
  AerosolCoeff.nc4
  ahi_himawari8.SpcCoeff.bin
  ahi_himawari8.TauCoeff.bin
  ahi_himawari9.SpcCoeff.bin
  ahi_himawari9.TauCoeff.bin
  airs281_aqua.SpcCoeff.bin
  airs281_aqua.TauCoeff.bin
  airs324_aqua.SpcCoeff.bin
  airs324_aqua.TauCoeff.bin
  airs_aqua.SpcCoeff.bin
  airs_aqua.TauCoeff.bin
  airs_g13.SpcCoeff.bin
  airs_g13.TauCoeff.bin
  airsM10_aqua.SpcCoeff.bin
  airsM10_aqua.TauCoeff.bin
  airsM11_aqua.SpcCoeff.bin
  airsM11_aqua.TauCoeff.bin
  airsM12_aqua.SpcCoeff.bin
  airsM12_aqua.TauCoeff.bin
  airsM1a_aqua.SpcCoeff.bin
  airsM1a_aqua.TauCoeff.bin
  airsM1b_aqua.SpcCoeff.bin
  airsM1b_aqua.TauCoeff.bin
  airsM2a_aqua.SpcCoeff.bin
  airsM2a_aqua.TauCoeff.bin
  airsM2b_aqua.SpcCoeff.bin
  airsM2b_aqua.TauCoeff.bin
  airsM3_aqua.SpcCoeff.bin
  airsM3_aqua.TauCoeff.bin
  airsM4a_aqua.SpcCoeff.bin
  airsM4a_aqua.TauCoeff.bin
  airsM4b_aqua.SpcCoeff.bin
  airsM4b_aqua.TauCoeff.bin
  airsM4c_aqua.SpcCoeff.bin
  airsM4c_aqua.TauCoeff.bin
  airsM4d_aqua.SpcCoeff.bin
  airsM4d_aqua.TauCoeff.bin
  airsM5_aqua.SpcCoeff.bin
  airsM5_aqua.TauCoeff.bin
  airsM6_aqua.SpcCoeff.bin
  airsM6_aqua.TauCoeff.bin
  airsM7_aqua.SpcCoeff.bin
  airsM7_aqua.TauCoeff.bin
  airsM8_aqua.SpcCoeff.bin
  airsM8_aqua.TauCoeff.bin
  airsM9_aqua.SpcCoeff.bin
  airsM9_aqua.TauCoeff.bin
  ami_gk2.SpcCoeff.bin
  ami_gk2.TauCoeff.bin
  amsr2_gcom-w1.SpcCoeff.bin
  amsr2_gcom-w1.TauCoeff.bin
  amsre_aqua.SpcCoeff.bin
  amsre_aqua.TauCoeff.bin
  amsua_aqua.SpcCoeff.bin
  amsua_aqua.TauCoeff.bin
  amsua_metop-a.SpcCoeff.bin
  amsua_metop-a.TauCoeff.bin
  amsua_metop-a_v2.ACCoeff.nc
  amsua_metop-a_v2.SpcCoeff.bin
  amsua_metop-b.SpcCoeff.bin
  amsua_metop-b.TauCoeff.bin
  amsua_metop-c.SpcCoeff.bin
  amsua_metop-c.SpcCoeff.noACC.bin
  amsua_metop-c.TauCoeff.bin
  amsua_metop-c_v2.ACCoeff.nc
  amsua_metop-c_v2.SpcCoeff.nc
  amsua_n15.SpcCoeff.bin
  amsua_n15.TauCoeff.bin
  amsua_n16.SpcCoeff.bin
  amsua_n16.TauCoeff.bin
  amsua_n17.SpcCoeff.bin
  amsua_n17.TauCoeff.bin
  amsua_n18.SpcCoeff.bin
  amsua_n18.TauCoeff.bin
  amsua_n19.SpcCoeff.bin
  amsua_n19.TauCoeff.bin
  amsub_n15.SpcCoeff.bin
  amsub_n15.TauCoeff.bin
  amsub_n16.SpcCoeff.bin
  amsub_n16.TauCoeff.bin
  amsub_n17.SpcCoeff.bin
  amsub_n17.TauCoeff.bin
  aster_terra.SpcCoeff.bin
  aster_terra.TauCoeff.bin
  atms_j2.SpcCoeff.bin
  atms_j2-srf.SpcCoeff.bin
  atms_j2-srf.TauCoeff.bin
  atms_j2.TauCoeff.bin
  atms_n20.SpcCoeff.bin
  atms_n20-srf.SpcCoeff.bin
  atms_n20-srf.TauCoeff.bin
  atms_n20.TauCoeff.bin
  atms_n21.SpcCoeff.bin
  atms_n21.SpcCoeff.nc
  atms_n21-srf.SpcCoeff.bin
  atms_n21-srf.SpcCoeff.nc
  atms_n21-srf.TauCoeff.bin
  atms_n21-srf.TauCoeff.nc
  atms_n21.TauCoeff.bin
  atms_n21.TauCoeff.nc
  atms-ng_v1.SpcCoeff.bin
  atms-ng_v1.TauCoeff.bin
  atms_npp.nasa.T-10_Vnom_LOpri.SpcCoeff.bin
  atms_npp.nasa.T-10_Vnom_LOpri.TauCoeff.bin
  atms_npp.nasa.T20_Vhi_LOpri.SpcCoeff.bin
  atms_npp.nasa.T20_Vhi_LOpri.TauCoeff.bin
  atms_npp.nasa.T20_Vlow_LOpri.SpcCoeff.bin
  atms_npp.nasa.T20_Vlow_LOpri.TauCoeff.bin
  atms_npp.nasa.T20_Vnom_LOpri.SpcCoeff.bin
  atms_npp.nasa.T20_Vnom_LOpri.TauCoeff.bin
  atms_npp.nasa.T50_Vnom_LOpri.SpcCoeff.bin
  atms_npp.nasa.T50_Vnom_LOpri.TauCoeff.bin
  atms_npp.SpcCoeff.bin
  atms_npp.TauCoeff.bin
  atsr1_ers1.SpcCoeff.bin
  atsr1_ers1.TauCoeff.bin
  atsr2_ers2.SpcCoeff.bin
  atsr2_ers2.TauCoeff.bin
  avhrr2_n06.SpcCoeff.bin
  avhrr2_n06.TauCoeff.bin
  avhrr2_n07.SpcCoeff.bin
  avhrr2_n07.TauCoeff.bin
  avhrr2_n08.SpcCoeff.bin
  avhrr2_n08.TauCoeff.bin
  avhrr2_n09.SpcCoeff.bin
  avhrr2_n09.TauCoeff.bin
  avhrr2_n10.SpcCoeff.bin
  avhrr2_n10.TauCoeff.bin
  avhrr2_n11.SpcCoeff.bin
  avhrr2_n11.TauCoeff.bin
  avhrr2_n12.SpcCoeff.bin
  avhrr2_n12.TauCoeff.bin
  avhrr2_n14.SpcCoeff.bin
  avhrr2_n14.TauCoeff.bin
  avhrr2_tirosn.SpcCoeff.bin
  avhrr2_tirosn.TauCoeff.bin
  avhrr3JM_n17.SpcCoeff.bin
  avhrr3JM_n17.TauCoeff.bin
  avhrr3JM_n18.SpcCoeff.bin
  avhrr3JM_n18.TauCoeff.bin
  avhrr3_metop-a.SpcCoeff.bin
  avhrr3_metop-a.TauCoeff.bin
  avhrr3_metop-b.SpcCoeff.bin
  avhrr3_metop-b.TauCoeff.bin
  avhrr3_metop-c.SpcCoeff.bin
  avhrr3_metop-c.TauCoeff.bin
  avhrr3_n15.SpcCoeff.bin
  avhrr3_n15.TauCoeff.bin
  avhrr3_n16.SpcCoeff.bin
  avhrr3_n16.TauCoeff.bin
  avhrr3_n17.SpcCoeff.bin
  avhrr3_n17.TauCoeff.bin
  avhrr3_n18.SpcCoeff.bin
  avhrr3_n18.TauCoeff.bin
  avhrr3_n19.SpcCoeff.bin
  avhrr3_n19.TauCoeff.bin
  CloudCoeff.bin
  CloudCoeff.GFDLFV3.-109z-1.bin
  CloudCoeff.GFDLFV3.-109z-1.nc4
  CloudCoeff_MW_2.4.0_a.nc4
  CloudCoeff_MW_2.4.0_exp_freq.nc4
  CloudCoeff_MW_2.4.0_exp.nc4
  CloudCoeff.nc4
  CloudCoeff_TAMU-07Sep2015.nc4
  CloudCoeff_TAMU-11Sep2014.bin
  CloudCoeff_TAMU-11Sep2014.nc4
  CloudCoeff.Thompson08.-109z-1.bin
  CloudCoeff.Thompson08.-109z-1.nc4
  CloudCoeff.WSM6.-109z-1.bin
  CloudCoeff.WSM6.-109z-1.nc4
  CloudCoeff.WSM6.MieSphere.bin
  CloudCoeff.WSM6.MieSphere.nc4
  cowvr_ors6.SpcCoeff.bin
  cowvr_ors6.TauCoeff.bin
  cpr_cloudsat.SpcCoeff.bin
  cris374_n20.SpcCoeff.bin
  cris374_n20.TauCoeff.bin
  cris374_npp.SpcCoeff.bin
  cris374_npp.TauCoeff.bin
  cris399_n20.SpcCoeff.bin
  cris399_n20.TauCoeff.bin
  cris399_npp.SpcCoeff.bin
  cris399_npp.TauCoeff.bin
  crisB1_n20.SpcCoeff.bin
  crisB1_n20.TauCoeff.bin
  crisB1_npp.SpcCoeff.bin
  crisB1_npp.TauCoeff.bin
  crisB2_n20.SpcCoeff.bin
  crisB2_n20.TauCoeff.bin
  crisB2_npp.SpcCoeff.bin
  crisB2_npp.TauCoeff.bin
  crisB3_n20.SpcCoeff.bin
  crisB3_n20.TauCoeff.bin
  crisB3_npp.SpcCoeff.bin
  crisB3_npp.TauCoeff.bin
  cris-fsr431_n20.SpcCoeff.bin
  cris-fsr431_n20.TauCoeff.bin
  cris-fsr431_npp.SpcCoeff.bin
  cris-fsr431_npp.TauCoeff.bin
  cris-fsrB1_n20.SpcCoeff.bin
  cris-fsrB1_n20.TauCoeff.bin
  cris-fsrB1_npp.SpcCoeff.bin
  cris-fsrB1_npp.TauCoeff.bin
  cris-fsrB2_n20.SpcCoeff.bin
  cris-fsrB2_n20.TauCoeff.bin
  cris-fsrB2_npp.SpcCoeff.bin
  cris-fsrB2_npp.TauCoeff.bin
  cris-fsrB3_n20.SpcCoeff.bin
  cris-fsrB3_n20.TauCoeff.bin
  cris-fsrB3_npp.SpcCoeff.bin
  cris-fsrB3_npp.TauCoeff.bin
  cris-fsr_j2.SpcCoeff.bin
  cris-fsr_j2.TauCoeff.bin
  cris-fsr_n20.SpcCoeff.bin
  cris-fsr_n20.TauCoeff.bin
  cris-fsr_n21.SpcCoeff.bin
  cris-fsr_n21.SpcCoeff.nc
  cris-fsr_n21.TauCoeff.bin
  cris-fsr_n21.TauCoeff.nc
  cris-fsr_npp.SpcCoeff.bin
  cris-fsr_npp.TauCoeff.bin
  cris_n20.SpcCoeff.bin
  cris_n20.TauCoeff.bin
  cris_npp.SpcCoeff.bin
  cris_npp.TauCoeff.bin
  dpr_gpm.SpcCoeff.bin
  eon_mw.v1.SpcCoeff.bin
  eon_mw.v1.TauCoeff.bin
  FASTEM4.MWwater.EmisCoeff.bin
  FASTEM5.MWwater.EmisCoeff.bin
  FASTEM6.MWwater.EmisCoeff.bin
  fci_mtg-i1.SpcCoeff.bin
  fci_mtg-i1.TauCoeff.bin
  geostorm_proposed.boxcar.SpcCoeff.bin
  geostorm_proposed.boxcar.TauCoeff.bin
  geostorm_proposed.gaussian.SpcCoeff.bin
  geostorm_proposed.gaussian.TauCoeff.bin
  giirsB1_fsr_fy4a.SpcCoeff.bin
  giirsB2_fsr_fy4a.SpcCoeff.bin
  gmi_gpm.SpcCoeff.bin
  gmi_gpm.TauCoeff.bin
  gmi_gpm.THI.SpcCoeff.bin
  gmi_gpm.THI.TauCoeff.bin
  gmi_gpm.TLO.SpcCoeff.bin
  gmi_gpm.TLO.TauCoeff.bin
  gmi_gpm.TNOM.SpcCoeff.bin
  gmi_gpm.TNOM.TauCoeff.bin
  gxs_geoxo_lw.SpcCoeff.bin
  gxs_geoxo_lw.TauCoeff.bin
  gxs_geoxo_mw.SpcCoeff.bin
  gxs_geoxo_mw.TauCoeff.bin
  hamsr_grip.SpcCoeff.bin
  hamsr_grip.TauCoeff.bin
  hirs2_n06.SpcCoeff.bin
  hirs2_n06.TauCoeff.bin
  hirs2_n07.SpcCoeff.bin
  hirs2_n07.TauCoeff.bin
  hirs2_n08.SpcCoeff.bin
  hirs2_n08.TauCoeff.bin
  hirs2_n09.SpcCoeff.bin
  hirs2_n09.TauCoeff.bin
  hirs2_n10.SpcCoeff.bin
  hirs2_n10.TauCoeff.bin
  hirs2_n11.SpcCoeff.bin
  hirs2_n11.TauCoeff.bin
  hirs2_n12.SpcCoeff.bin
  hirs2_n12.TauCoeff.bin
  hirs2_n14.SpcCoeff.bin
  hirs2_n14.TauCoeff.bin
  hirs2_tirosn.SpcCoeff.bin
  hirs2_tirosn.TauCoeff.bin
  hirs2-UWS_n06.SpcCoeff.bin
  hirs2-UWS_n06.TauCoeff.bin
  hirs2-UWS_n07.SpcCoeff.bin
  hirs2-UWS_n07.TauCoeff.bin
  hirs2-UWS_n09.SpcCoeff.bin
  hirs2-UWS_n09.TauCoeff.bin
  hirs2-UWS_n10.SpcCoeff.bin
  hirs2-UWS_n10.TauCoeff.bin
  hirs2-UWS_n11.SpcCoeff.bin
  hirs2-UWS_n11.TauCoeff.bin
  hirs2-UWS_n12.SpcCoeff.bin
  hirs2-UWS_n12.TauCoeff.bin
  hirs2-UWS_n14.SpcCoeff.bin
  hirs2-UWS_n14.TauCoeff.bin
  hirs3_n15.SpcCoeff.bin
  hirs3_n15.TauCoeff.bin
  hirs3_n16.SpcCoeff.bin
  hirs3_n16.TauCoeff.bin
  hirs3_n17.SpcCoeff.bin
  hirs3_n17.TauCoeff.bin
  hirs3-UWS_n15.SpcCoeff.bin
  hirs3-UWS_n15.TauCoeff.bin
  hirs3-UWS_n16.SpcCoeff.bin
  hirs3-UWS_n16.TauCoeff.bin
  hirs3-UWS_n17.SpcCoeff.bin
  hirs3-UWS_n17.TauCoeff.bin
  hirs4_metop-a.SpcCoeff.bin
  hirs4_metop-a.TauCoeff.bin
  hirs4_metop-b.SpcCoeff.bin
  hirs4_metop-b.TauCoeff.bin
  hirs4_n18.SpcCoeff.bin
  hirs4_n18.TauCoeff.bin
  hirs4_n19.SpcCoeff.bin
  hirs4_n19.TauCoeff.bin
  hirs4-UWS_metop-a.SpcCoeff.bin
  hirs4-UWS_metop-a.TauCoeff.bin
  hirs4-UWS_metop-b.SpcCoeff.bin
  hirs4-UWS_metop-b.TauCoeff.bin
  hirs4-UWS_n18.SpcCoeff.bin
  hirs4-UWS_n18.TauCoeff.bin
  hirs4-UWS_n19.SpcCoeff.bin
  hirs4-UWS_n19.TauCoeff.bin
  hsb_aqua.SpcCoeff.bin
  hsb_aqua.TauCoeff.bin
  iasi300_metop-a.SpcCoeff.bin
  iasi300_metop-a.TauCoeff.bin
  iasi300_metop-b.SpcCoeff.bin
  iasi300_metop-b.TauCoeff.bin
  iasi300_metop-c.SpcCoeff.bin
  iasi300_metop-c.TauCoeff.bin
  iasi316_metop-a.SpcCoeff.bin
  iasi316_metop-a.TauCoeff.bin
  iasi316_metop-b.SpcCoeff.bin
  iasi316_metop-b.TauCoeff.bin
  iasi316_metop-c.SpcCoeff.bin
  iasi316_metop-c.TauCoeff.bin
  iasi616_metop-a.SpcCoeff.bin
  iasi616_metop-a.TauCoeff.bin
  iasi616_metop-b.SpcCoeff.bin
  iasi616_metop-b.TauCoeff.bin
  iasi616_metop-c.SpcCoeff.bin
  iasi616_metop-c.TauCoeff.bin
  iasiB1_metop-a.SpcCoeff.bin
  iasiB1_metop-a.TauCoeff.bin
  iasiB1_metop-b.SpcCoeff.bin
  iasiB1_metop-b.TauCoeff.bin
  iasiB1_metop-c.SpcCoeff.bin
  iasiB1_metop-c.TauCoeff.bin
  iasiB2_metop-a.SpcCoeff.bin
  iasiB2_metop-a.TauCoeff.bin
  iasiB2_metop-b.SpcCoeff.bin
  iasiB2_metop-b.TauCoeff.bin
  iasiB2_metop-c.SpcCoeff.bin
  iasiB2_metop-c.TauCoeff.bin
  iasiB3_metop-a.SpcCoeff.bin
  iasiB3_metop-a.TauCoeff.bin
  iasiB3_metop-b.SpcCoeff.bin
  iasiB3_metop-b.TauCoeff.bin
  iasiB3_metop-c.SpcCoeff.bin
  iasiB3_metop-c.TauCoeff.bin
  iasi_g13.SpcCoeff.bin
  iasi_g13.TauCoeff.bin
  iasi_metop-a.SpcCoeff.bin
  iasi_metop-a.TauCoeff.bin
  iasi_metop-b.SpcCoeff.bin
  iasi_metop-b.TauCoeff.bin
  iasi_metop-c.SpcCoeff.bin
  iasi_metop-c.TauCoeff.bin
  iasi-ng_metop-sg-a1.SpcCoeff.bin
  iasi-ng_metop-sg-a1.TauCoeff.bin
  IGBP.IRland.EmisCoeff.bin
  IGBP.VISland.EmisCoeff.bin
  imgrD1_g13.SpcCoeff.bin
  imgrD1_g13.TauCoeff.bin
  imgrD1_g14.SpcCoeff.bin
  imgrD1_g14.TauCoeff.bin
  imgrD1_g15.SpcCoeff.bin
  imgrD1_g15.TauCoeff.bin
  imgrD1S1_g13.SpcCoeff.bin
  imgrD1S2_g13.SpcCoeff.bin
  imgrD2_g13.SpcCoeff.bin
  imgrD2_g13.TauCoeff.bin
  imgrD2_g14.SpcCoeff.bin
  imgrD2_g14.TauCoeff.bin
  imgrD2_g15.SpcCoeff.bin
  imgrD2_g15.TauCoeff.bin
  imgrD2S1_g13.SpcCoeff.bin
  imgrD2S2_g13.SpcCoeff.bin
  imgr_g08.SpcCoeff.bin
  imgr_g08.TauCoeff.bin
  imgr_g09.SpcCoeff.bin
  imgr_g09.TauCoeff.bin
  imgr_g10.SpcCoeff.bin
  imgr_g10.TauCoeff.bin
  imgr_g11.SpcCoeff.bin
  imgr_g11.TauCoeff.bin
  imgr_g12.SpcCoeff.bin
  imgr_g12.TauCoeff.bin
  imgr_g13.SpcCoeff.bin
  imgr_g13.TauCoeff.bin
  imgr_g14.SpcCoeff.bin
  imgr_g14.TauCoeff.bin
  imgr_g15.SpcCoeff.bin
  imgr_g15.TauCoeff.bin
  imgr_insat3d.SpcCoeff.bin
  imgr_insat-3ds.SpcCoeff.bin
  imgr_insat-3ds.TauCoeff.bin
  imgr_insat3d.TauCoeff.bin
  imgr_mt1r.SpcCoeff.bin
  imgr_mt1r.TauCoeff.bin
  imgr_mt2.SpcCoeff.bin
  imgr_mt2.TauCoeff.bin
  imgrS1_g13.SpcCoeff.bin
  imgrS2_g13.SpcCoeff.bin
  iras_fy3a.SpcCoeff.bin
  iras_fy3a.TauCoeff.bin
  iras_fy3b.SpcCoeff.bin
  iras_fy3b.TauCoeff.bin
  ivissr_fy2c.SpcCoeff.bin
  ivissr_fy2c.TauCoeff.bin
  ivissr_fy2d.SpcCoeff.bin
  ivissr_fy2d.TauCoeff.bin
  ivissr_fy2e.SpcCoeff.bin
  ivissr_fy2e.TauCoeff.bin
  ivissr_fy2f.SpcCoeff.bin
  ivissr_fy2f.TauCoeff.bin
  madras_meghat.SpcCoeff.bin
  madras_meghat.TauCoeff.bin
  masc_cubesat.SpcCoeff.bin
  masc_cubesat.TauCoeff.bin
  mersiD01_fy3a.SpcCoeff.bin
  mersiD01_fy3a.TauCoeff.bin
  mersiD02_fy3a.SpcCoeff.bin
  mersiD02_fy3a.TauCoeff.bin
  mersiD03_fy3a.SpcCoeff.bin
  mersiD03_fy3a.TauCoeff.bin
  mersiD04_fy3a.SpcCoeff.bin
  mersiD04_fy3a.TauCoeff.bin
  mersiD05_fy3a.SpcCoeff.bin
  mersiD05_fy3a.TauCoeff.bin
  mersiD06_fy3a.SpcCoeff.bin
  mersiD06_fy3a.TauCoeff.bin
  mersiD07_fy3a.SpcCoeff.bin
  mersiD07_fy3a.TauCoeff.bin
  mersiD08_fy3a.SpcCoeff.bin
  mersiD08_fy3a.TauCoeff.bin
  mersiD09_fy3a.SpcCoeff.bin
  mersiD09_fy3a.TauCoeff.bin
  mersiD10_fy3a.SpcCoeff.bin
  mersiD10_fy3a.TauCoeff.bin
  mersiD11_fy3a.SpcCoeff.bin
  mersiD11_fy3a.TauCoeff.bin
  mersiD12_fy3a.SpcCoeff.bin
  mersiD12_fy3a.TauCoeff.bin
  mersiD13_fy3a.SpcCoeff.bin
  mersiD13_fy3a.TauCoeff.bin
  mersiD14_fy3a.SpcCoeff.bin
  mersiD14_fy3a.TauCoeff.bin
  mersiD15_fy3a.SpcCoeff.bin
  mersiD15_fy3a.TauCoeff.bin
  mersiD16_fy3a.SpcCoeff.bin
  mersiD16_fy3a.TauCoeff.bin
  mersiD17_fy3a.SpcCoeff.bin
  mersiD17_fy3a.TauCoeff.bin
  mersiD18_fy3a.SpcCoeff.bin
  mersiD18_fy3a.TauCoeff.bin
  mersiD19_fy3a.SpcCoeff.bin
  mersiD19_fy3a.TauCoeff.bin
  mersiD20_fy3a.SpcCoeff.bin
  mersiD20_fy3a.TauCoeff.bin
  mersiD21_fy3a.SpcCoeff.bin
  mersiD21_fy3a.TauCoeff.bin
  mersiD22_fy3a.SpcCoeff.bin
  mersiD22_fy3a.TauCoeff.bin
  mersiD23_fy3a.SpcCoeff.bin
  mersiD23_fy3a.TauCoeff.bin
  mersiD24_fy3a.SpcCoeff.bin
  mersiD24_fy3a.TauCoeff.bin
  mersiD25_fy3a.SpcCoeff.bin
  mersiD25_fy3a.TauCoeff.bin
  mersiD26_fy3a.SpcCoeff.bin
  mersiD26_fy3a.TauCoeff.bin
  mersiD27_fy3a.SpcCoeff.bin
  mersiD27_fy3a.TauCoeff.bin
  mersiD28_fy3a.SpcCoeff.bin
  mersiD28_fy3a.TauCoeff.bin
  mersiD29_fy3a.SpcCoeff.bin
  mersiD29_fy3a.TauCoeff.bin
  mersiD30_fy3a.SpcCoeff.bin
  mersiD30_fy3a.TauCoeff.bin
  mersiD31_fy3a.SpcCoeff.bin
  mersiD31_fy3a.TauCoeff.bin
  mersiD32_fy3a.SpcCoeff.bin
  mersiD32_fy3a.TauCoeff.bin
  mersiD33_fy3a.SpcCoeff.bin
  mersiD33_fy3a.TauCoeff.bin
  mersiD34_fy3a.SpcCoeff.bin
  mersiD34_fy3a.TauCoeff.bin
  mersiD35_fy3a.SpcCoeff.bin
  mersiD35_fy3a.TauCoeff.bin
  mersiD36_fy3a.SpcCoeff.bin
  mersiD36_fy3a.TauCoeff.bin
  mersiD37_fy3a.SpcCoeff.bin
  mersiD37_fy3a.TauCoeff.bin
  mersiD38_fy3a.SpcCoeff.bin
  mersiD38_fy3a.TauCoeff.bin
  mersiD39_fy3a.SpcCoeff.bin
  mersiD39_fy3a.TauCoeff.bin
  mersiD40_fy3a.SpcCoeff.bin
  mersiD40_fy3a.TauCoeff.bin
  mersi_fy3a.SpcCoeff.bin
  mersi_fy3a.TauCoeff.bin
  metimage_metop-sg-a1.SpcCoeff.bin
  metimage_metop-sg-a1.TauCoeff.bin
  mhs_metop-a.SpcCoeff.bin
  mhs_metop-a.TauCoeff.bin
  mhs_metop-b.SpcCoeff.bin
  mhs_metop-b.TauCoeff.bin
  mhs_metop-c.SpcCoeff.bin
  mhs_metop-c.SpcCoeff.nc
  mhs_metop-c.SpcCoeff.noACC.bin
  mhs_metop-c.TauCoeff.bin
  mhs_metop-c_v2.ACCoeff.nc
  mhs_n18.SpcCoeff.bin
  mhs_n18.TauCoeff.bin
  mhs_n19.SpcCoeff.bin
  mhs_n19.TauCoeff.bin
  micromas_cs00.SpcCoeff.bin
  micromas_cs00.TauCoeff.bin
  micromas_cs01.SpcCoeff.bin
  micromas_cs01.TauCoeff.bin
  micromas_cs02.SpcCoeff.bin
  micromas_cs02.TauCoeff.bin
  micromas_cs03.SpcCoeff.bin
  micromas_cs03.TauCoeff.bin
  micromas_cs04.SpcCoeff.bin
  micromas_cs04.TauCoeff.bin
  micromas_cs05.SpcCoeff.bin
  micromas_cs05.TauCoeff.bin
  mi-l_coms.SpcCoeff.bin
  mi-l_coms.TauCoeff.bin
  mi-l_coms.v2.SpcCoeff.bin
  mi-l_coms.v2.TauCoeff.bin
  mi-lD01_coms.SpcCoeff.bin
  mi-lD01_coms.TauCoeff.bin
  mi-lD02_coms.SpcCoeff.bin
  mi-lD02_coms.TauCoeff.bin
  mi-lD03_coms.SpcCoeff.bin
  mi-lD03_coms.TauCoeff.bin
  mi-lD04_coms.SpcCoeff.bin
  mi-lD04_coms.TauCoeff.bin
  mi-m_coms.SpcCoeff.bin
  mi-m_coms.TauCoeff.bin
  mi-mD01_coms.SpcCoeff.bin
  mi-mD01_coms.TauCoeff.bin
  mi-mD02_coms.SpcCoeff.bin
  mi-mD02_coms.TauCoeff.bin
  mi-mD03_coms.SpcCoeff.bin
  mi-mD03_coms.TauCoeff.bin
  mi-mD04_coms.SpcCoeff.bin
  mi-mD04_coms.TauCoeff.bin
  miras_smos.SpcCoeff.bin
  miras_smos.TauCoeff.bin
  modis_aqua.SpcCoeff.bin
  modis_aqua.TauCoeff.bin
  modisD01_aqua.SpcCoeff.bin
  modisD01_aqua.TauCoeff.bin
  modisD01S_aqua.SpcCoeff.bin
  modisD01S_aqua.TauCoeff.bin
  modisD01Shift1_aqua.SpcCoeff.bin
  modisD01Shift1_aqua.TauCoeff.bin
  modisD01Shift1_terra.SpcCoeff.bin
  modisD01Shift1_terra.TauCoeff.bin
  modisD01Shift2_aqua.SpcCoeff.bin
  modisD01Shift2_aqua.TauCoeff.bin
  modisD01Shift2_terra.SpcCoeff.bin
  modisD01Shift2_terra.TauCoeff.bin
  modisD01S_terra.SpcCoeff.bin
  modisD01S_terra.TauCoeff.bin
  modisD01_terra.SpcCoeff.bin
  modisD01_terra.TauCoeff.bin
  modisD02_aqua.SpcCoeff.bin
  modisD02_aqua.TauCoeff.bin
  modisD02S_aqua.SpcCoeff.bin
  modisD02S_aqua.TauCoeff.bin
  modisD02Shift1_aqua.SpcCoeff.bin
  modisD02Shift1_aqua.TauCoeff.bin
  modisD02Shift1_terra.SpcCoeff.bin
  modisD02Shift1_terra.TauCoeff.bin
  modisD02Shift2_aqua.SpcCoeff.bin
  modisD02Shift2_aqua.TauCoeff.bin
  modisD02Shift2_terra.SpcCoeff.bin
  modisD02Shift2_terra.TauCoeff.bin
  modisD02S_terra.SpcCoeff.bin
  modisD02S_terra.TauCoeff.bin
  modisD02_terra.SpcCoeff.bin
  modisD02_terra.TauCoeff.bin
  modisD03_aqua.SpcCoeff.bin
  modisD03_aqua.TauCoeff.bin
  modisD03S_aqua.SpcCoeff.bin
  modisD03S_aqua.TauCoeff.bin
  modisD03Shift1_aqua.SpcCoeff.bin
  modisD03Shift1_aqua.TauCoeff.bin
  modisD03Shift1_terra.SpcCoeff.bin
  modisD03Shift1_terra.TauCoeff.bin
  modisD03Shift2_aqua.SpcCoeff.bin
  modisD03Shift2_aqua.TauCoeff.bin
  modisD03Shift2_terra.SpcCoeff.bin
  modisD03Shift2_terra.TauCoeff.bin
  modisD03S_terra.SpcCoeff.bin
  modisD03S_terra.TauCoeff.bin
  modisD03_terra.SpcCoeff.bin
  modisD03_terra.TauCoeff.bin
  modisD04_aqua.SpcCoeff.bin
  modisD04_aqua.TauCoeff.bin
  modisD04S_aqua.SpcCoeff.bin
  modisD04S_aqua.TauCoeff.bin
  modisD04Shift1_aqua.SpcCoeff.bin
  modisD04Shift1_aqua.TauCoeff.bin
  modisD04Shift1_terra.SpcCoeff.bin
  modisD04Shift1_terra.TauCoeff.bin
  modisD04Shift2_aqua.SpcCoeff.bin
  modisD04Shift2_aqua.TauCoeff.bin
  modisD04Shift2_terra.SpcCoeff.bin
  modisD04Shift2_terra.TauCoeff.bin
  modisD04S_terra.SpcCoeff.bin
  modisD04S_terra.TauCoeff.bin
  modisD04_terra.SpcCoeff.bin
  modisD04_terra.TauCoeff.bin
  modisD05_aqua.SpcCoeff.bin
  modisD05_aqua.TauCoeff.bin
  modisD05S_aqua.SpcCoeff.bin
  modisD05S_aqua.TauCoeff.bin
  modisD05Shift1_aqua.SpcCoeff.bin
  modisD05Shift1_aqua.TauCoeff.bin
  modisD05Shift1_terra.SpcCoeff.bin
  modisD05Shift1_terra.TauCoeff.bin
  modisD05Shift2_aqua.SpcCoeff.bin
  modisD05Shift2_aqua.TauCoeff.bin
  modisD05Shift2_terra.SpcCoeff.bin
  modisD05Shift2_terra.TauCoeff.bin
  modisD05S_terra.SpcCoeff.bin
  modisD05S_terra.TauCoeff.bin
  modisD05_terra.SpcCoeff.bin
  modisD05_terra.TauCoeff.bin
  modisD06_aqua.SpcCoeff.bin
  modisD06_aqua.TauCoeff.bin
  modisD06S_aqua.SpcCoeff.bin
  modisD06S_aqua.TauCoeff.bin
  modisD06Shift1_aqua.SpcCoeff.bin
  modisD06Shift1_aqua.TauCoeff.bin
  modisD06Shift1_terra.SpcCoeff.bin
  modisD06Shift1_terra.TauCoeff.bin
  modisD06Shift2_aqua.SpcCoeff.bin
  modisD06Shift2_aqua.TauCoeff.bin
  modisD06Shift2_terra.SpcCoeff.bin
  modisD06Shift2_terra.TauCoeff.bin
  modisD06S_terra.SpcCoeff.bin
  modisD06S_terra.TauCoeff.bin
  modisD06_terra.SpcCoeff.bin
  modisD06_terra.TauCoeff.bin
  modisD07_aqua.SpcCoeff.bin
  modisD07_aqua.TauCoeff.bin
  modisD07S_aqua.SpcCoeff.bin
  modisD07S_aqua.TauCoeff.bin
  modisD07Shift1_aqua.SpcCoeff.bin
  modisD07Shift1_aqua.TauCoeff.bin
  modisD07Shift1_terra.SpcCoeff.bin
  modisD07Shift1_terra.TauCoeff.bin
  modisD07Shift2_aqua.SpcCoeff.bin
  modisD07Shift2_aqua.TauCoeff.bin
  modisD07Shift2_terra.SpcCoeff.bin
  modisD07Shift2_terra.TauCoeff.bin
  modisD07S_terra.SpcCoeff.bin
  modisD07S_terra.TauCoeff.bin
  modisD07_terra.SpcCoeff.bin
  modisD07_terra.TauCoeff.bin
  modisD08_aqua.SpcCoeff.bin
  modisD08_aqua.TauCoeff.bin
  modisD08S_aqua.SpcCoeff.bin
  modisD08S_aqua.TauCoeff.bin
  modisD08Shift1_aqua.SpcCoeff.bin
  modisD08Shift1_aqua.TauCoeff.bin
  modisD08Shift1_terra.SpcCoeff.bin
  modisD08Shift1_terra.TauCoeff.bin
  modisD08Shift2_aqua.SpcCoeff.bin
  modisD08Shift2_aqua.TauCoeff.bin
  modisD08Shift2_terra.SpcCoeff.bin
  modisD08Shift2_terra.TauCoeff.bin
  modisD08S_terra.SpcCoeff.bin
  modisD08S_terra.TauCoeff.bin
  modisD08_terra.SpcCoeff.bin
  modisD08_terra.TauCoeff.bin
  modisD09_aqua.SpcCoeff.bin
  modisD09_aqua.TauCoeff.bin
  modisD09S_aqua.SpcCoeff.bin
  modisD09S_aqua.TauCoeff.bin
  modisD09Shift1_aqua.SpcCoeff.bin
  modisD09Shift1_aqua.TauCoeff.bin
  modisD09Shift1_terra.SpcCoeff.bin
  modisD09Shift1_terra.TauCoeff.bin
  modisD09Shift2_aqua.SpcCoeff.bin
  modisD09Shift2_aqua.TauCoeff.bin
  modisD09Shift2_terra.SpcCoeff.bin
  modisD09Shift2_terra.TauCoeff.bin
  modisD09S_terra.SpcCoeff.bin
  modisD09S_terra.TauCoeff.bin
  modisD09_terra.SpcCoeff.bin
  modisD09_terra.TauCoeff.bin
  modisD10_aqua.SpcCoeff.bin
  modisD10_aqua.TauCoeff.bin
  modisD10S_aqua.SpcCoeff.bin
  modisD10S_aqua.TauCoeff.bin
  modisD10Shift1_aqua.SpcCoeff.bin
  modisD10Shift1_aqua.TauCoeff.bin
  modisD10Shift1_terra.SpcCoeff.bin
  modisD10Shift1_terra.TauCoeff.bin
  modisD10Shift2_aqua.SpcCoeff.bin
  modisD10Shift2_aqua.TauCoeff.bin
  modisD10Shift2_terra.SpcCoeff.bin
  modisD10Shift2_terra.TauCoeff.bin
  modisD10S_terra.SpcCoeff.bin
  modisD10S_terra.TauCoeff.bin
  modisD10_terra.SpcCoeff.bin
  modisD10_terra.TauCoeff.bin
  modisS_aqua.SpcCoeff.bin
  modisS_aqua.TauCoeff.bin
  modisShift1_aqua.SpcCoeff.bin
  modisShift1_aqua.TauCoeff.bin
  modisShift1_terra.SpcCoeff.bin
  modisShift1_terra.TauCoeff.bin
  modisShift2_aqua.SpcCoeff.bin
  modisShift2_aqua.TauCoeff.bin
  modisShift2_terra.SpcCoeff.bin
  modisShift2_terra.TauCoeff.bin
  modisS_terra.SpcCoeff.bin
  modisS_terra.TauCoeff.bin
  modis_terra.SpcCoeff.bin
  modis_terra.TauCoeff.bin
  msu_n06.SpcCoeff.bin
  msu_n06.TauCoeff.bin
  msu_n07.SpcCoeff.bin
  msu_n07.TauCoeff.bin
  msu_n08.SpcCoeff.bin
  msu_n08.TauCoeff.bin
  msu_n09.SpcCoeff.bin
  msu_n09.TauCoeff.bin
  msu_n10.SpcCoeff.bin
  msu_n10.TauCoeff.bin
  msu_n11.SpcCoeff.bin
  msu_n11.TauCoeff.bin
  msu_n12.SpcCoeff.bin
  msu_n12.TauCoeff.bin
  msu_n14.SpcCoeff.bin
  msu_n14.TauCoeff.bin
  msu_tirosn.SpcCoeff.bin
  msu_tirosn.TauCoeff.bin
  mviriBKUP_m03.SpcCoeff.bin
  mviriBKUP_m03.TauCoeff.bin
  mviriBKUP_m04.SpcCoeff.bin
  mviriBKUP_m04.TauCoeff.bin
  mviriBKUP_m05.SpcCoeff.bin
  mviriBKUP_m05.TauCoeff.bin
  mviriBKUP_m06.SpcCoeff.bin
  mviriBKUP_m06.TauCoeff.bin
  mviriBKUP_m07.SpcCoeff.bin
  mviriBKUP_m07.TauCoeff.bin
  mviriNOM_m03.SpcCoeff.bin
  mviriNOM_m03.TauCoeff.bin
  mviriNOM_m04.SpcCoeff.bin
  mviriNOM_m04.TauCoeff.bin
  mviriNOM_m05.SpcCoeff.bin
  mviriNOM_m05.TauCoeff.bin
  mviriNOM_m06.SpcCoeff.bin
  mviriNOM_m06.TauCoeff.bin
  mviriNOM_m07.SpcCoeff.bin
  mviriNOM_m07.TauCoeff.bin
  mwhs_fy3a.SpcCoeff.bin
  mwhs_fy3a.TauCoeff.bin
  mwhs_fy3b.SpcCoeff.bin
  mwhs_fy3b.TauCoeff.bin
  mwi_metop-sg-a1.SpcCoeff.bin
  mwi_metop-sg-a1.TauCoeff.bin
  mwi_wsf-m1.SpcCoeff.bin
  mwi_wsf-m1.TauCoeff.bin
  mwri_fy3a.SpcCoeff.bin
  mwri_fy3a.TauCoeff.bin
  mwri_fy3b.SpcCoeff.bin
  mwri_fy3b.TauCoeff.bin
  mws_metop-sg-a1.SpcCoeff.bin
  mwts_fy3a.SpcCoeff.bin
  mwts_fy3a.TauCoeff.bin
  mwts_fy3b.SpcCoeff.bin
  mwts_fy3b.TauCoeff.bin
  MWwaterLUT.bin
  Nalli2.IRwater.EmisCoeff.bin
  Nalli.IRsnow.EmisCoeff.bin
  Nalli.IRwater.EmisCoeff.bin
  NPOESS.IRice.EmisCoeff.bin
  NPOESS.IRland.EmisCoeff.bin
  NPOESS.IRsnow.EmisCoeff.bin
  NPOESS.VISice.EmisCoeff.bin
  NPOESS.VISland.EmisCoeff.bin
  NPOESS.VISsnow.EmisCoeff.bin
  NPOESS.VISwater.EmisCoeff.bin
  radiometer_smap.SpcCoeff.bin
  radiometer_smap.TauCoeff.bin
  saphir_meghat.SpcCoeff.bin
  saphir_meghat.TauCoeff.bin
  seviri_m08.SpcCoeff.bin
  seviri_m08.TauCoeff.bin
  seviri_m09.SpcCoeff.bin
  seviri_m09.TauCoeff.bin
  seviri_m10.SpcCoeff.bin
  seviri_m10.TauCoeff.bin
  seviri_m11.SpcCoeff.bin
  seviri_m11.TauCoeff.bin
  slstr_sentinel3a.SpcCoeff.bin
  slstr_sentinel3a.TauCoeff.bin
  sndrD1_g10.SpcCoeff.bin
  sndrD1_g10.TauCoeff.bin
  sndrD1_g11.SpcCoeff.bin
  sndrD1_g11.TauCoeff.bin
  sndrD1_g12.SpcCoeff.bin
  sndrD1_g12.TauCoeff.bin
  sndrD1_g13.SpcCoeff.bin
  sndrD1_g13.TauCoeff.bin
  sndrD1_g14.SpcCoeff.bin
  sndrD1_g14.TauCoeff.bin
  sndrD1_g15.SpcCoeff.bin
  sndrD1_g15.TauCoeff.bin
  sndrD2_g10.SpcCoeff.bin
  sndrD2_g10.TauCoeff.bin
  sndrD2_g11.SpcCoeff.bin
  sndrD2_g11.TauCoeff.bin
  sndrD2_g12.SpcCoeff.bin
  sndrD2_g12.TauCoeff.bin
  sndrD2_g13.SpcCoeff.bin
  sndrD2_g13.TauCoeff.bin
  sndrD2_g14.SpcCoeff.bin
  sndrD2_g14.TauCoeff.bin
  sndrD2_g15.SpcCoeff.bin
  sndrD2_g15.TauCoeff.bin
  sndrD3_g10.SpcCoeff.bin
  sndrD3_g10.TauCoeff.bin
  sndrD3_g11.SpcCoeff.bin
  sndrD3_g11.TauCoeff.bin
  sndrD3_g12.SpcCoeff.bin
  sndrD3_g12.TauCoeff.bin
  sndrD3_g13.SpcCoeff.bin
  sndrD3_g13.TauCoeff.bin
  sndrD3_g14.SpcCoeff.bin
  sndrD3_g14.TauCoeff.bin
  sndrD3_g15.SpcCoeff.bin
  sndrD3_g15.TauCoeff.bin
  sndrD4_g10.SpcCoeff.bin
  sndrD4_g10.TauCoeff.bin
  sndrD4_g11.SpcCoeff.bin
  sndrD4_g11.TauCoeff.bin
  sndrD4_g12.SpcCoeff.bin
  sndrD4_g12.TauCoeff.bin
  sndrD4_g13.SpcCoeff.bin
  sndrD4_g13.TauCoeff.bin
  sndrD4_g14.SpcCoeff.bin
  sndrD4_g14.TauCoeff.bin
  sndrD4_g15.SpcCoeff.bin
  sndrD4_g15.TauCoeff.bin
  sndr_g08.SpcCoeff.bin
  sndr_g08.TauCoeff.bin
  sndr_g09.SpcCoeff.bin
  sndr_g09.TauCoeff.bin
  sndr_g10.SpcCoeff.bin
  sndr_g10.TauCoeff.bin
  sndr_g11.SpcCoeff.bin
  sndr_g11.TauCoeff.bin
  sndr_g12.SpcCoeff.bin
  sndr_g12.TauCoeff.bin
  sndr_g13.SpcCoeff.bin
  sndr_g13.TauCoeff.bin
  sndr_g14.SpcCoeff.bin
  sndr_g14.TauCoeff.bin
  sndr_g15.SpcCoeff.bin
  sndr_g15.TauCoeff.bin
  sndr_insat3d.SpcCoeff.bin
  sndr_insat-3ds.SpcCoeff.bin
  sndr_insat-3ds.TauCoeff.bin
  sndr_insat3d.TauCoeff.bin
  ssmi_f08.SpcCoeff.bin
  ssmi_f08.TauCoeff.bin
  ssmi_f10.SpcCoeff.bin
  ssmi_f10.TauCoeff.bin
  ssmi_f11.SpcCoeff.bin
  ssmi_f11.TauCoeff.bin
  ssmi_f13.SpcCoeff.bin
  ssmi_f13.TauCoeff.bin
  ssmi_f14.SpcCoeff.bin
  ssmi_f14.TauCoeff.bin
  ssmi_f15.SpcCoeff.bin
  ssmi_f15.TauCoeff.bin
  ssmis_f16.SpcCoeff.bin
  ssmis_f16.TauCoeff.bin
  ssmis_f16.v1-boxcar.SpcCoeff.bin
  ssmis_f16.v1-boxcar.TauCoeff.bin
  ssmis_f16.v2-ff_passband.SpcCoeff.bin
  ssmis_f16.v2-ff_passband.TauCoeff.bin
  ssmis_f16.v3-eff_passband.SpcCoeff.bin
  ssmis_f16.v3-eff_passband.TauCoeff.bin
  ssmis_f17.SpcCoeff.bin
  ssmis_f17.TauCoeff.bin
  ssmis_f17.v1-boxcar.SpcCoeff.bin
  ssmis_f17.v1-boxcar.TauCoeff.bin
  ssmis_f17.v2-ff_passband.SpcCoeff.bin
  ssmis_f17.v2-ff_passband.TauCoeff.bin
  ssmis_f18.SpcCoeff.bin
  ssmis_f18.TauCoeff.bin
  ssmis_f18.v1-boxcar.SpcCoeff.bin
  ssmis_f18.v1-boxcar.TauCoeff.bin
  ssmis_f18.v2-ff_passband.SpcCoeff.bin
  ssmis_f18.v2-ff_passband.TauCoeff.bin
  ssmis_f19.SpcCoeff.bin
  ssmis_f19.TauCoeff.bin
  ssmis_f19.v1-boxcar.SpcCoeff.bin
  ssmis_f19.v1-boxcar.TauCoeff.bin
  ssmis_f19.v2-ff_passband.SpcCoeff.bin
  ssmis_f19.v2-ff_passband.TauCoeff.bin
  ssmis_f20.SpcCoeff.bin
  ssmis_f20.TauCoeff.bin
  ssmis_f20.v1-boxcar.SpcCoeff.bin
  ssmis_f20.v1-boxcar.TauCoeff.bin
  ssmis_f20.v2-ff_passband.SpcCoeff.bin
  ssmis_f20.v2-ff_passband.TauCoeff.bin
  ssmt1_f13.SpcCoeff.bin
  ssmt1_f13.TauCoeff.bin
  ssmt1_f15.SpcCoeff.bin
  ssmt1_f15.TauCoeff.bin
  ssmt2_f14.SpcCoeff.bin
  ssmt2_f14.TauCoeff.bin
  ssmt2_f15.SpcCoeff.bin
  ssmt2_f15.TauCoeff.bin
  ssu_n06.SpcCoeff.bin
  ssu_n06.TauCoeff.bin
  ssu_n07.SpcCoeff.bin
  ssu_n07.TauCoeff.bin
  ssu_n08.SpcCoeff.bin
  ssu_n08.TauCoeff.bin
  ssu_n09.SpcCoeff.bin
  ssu_n09.TauCoeff.bin
  ssu_n11.SpcCoeff.bin
  ssu_n11.TauCoeff.bin
  ssu_n14.SpcCoeff.bin
  ssu_n14.TauCoeff.bin
  ssu_pseudo.SpcCoeff.bin
  ssu_pseudo.TauCoeff.bin
  ssu_tirosn.SpcCoeff.bin
  ssu_tirosn.TauCoeff.bin
  tempest-D_cubesat.SpcCoeff.bin
  tempest-D_cubesat.TauCoeff.bin
  tmi_trmm.SpcCoeff.bin
  tmi_trmm.TauCoeff.bin
  tms_tomorrow-s01_v4.SpcCoeff.bin
  tms_tomorrow-s02_v4.SpcCoeff.bin
  tms_tomorrow-s03_v4.SpcCoeff.bin
  tms_tomorrow-s04_v4.SpcCoeff.bin
  tms_tomorrow-s04_v4.TauCoeff.bin
  tms_tomorrow-s05_v4.SpcCoeff.bin
  tms_tomorrow-s05_v4.TauCoeff.bin
  tms_tomorrow-s06_v4.SpcCoeff.bin
  tms_tomorrow-s06_v4.TauCoeff.bin
  tms_tropics-01.SpcCoeff.bin
  tms_tropics-01.TauCoeff.bin
  tms_tropics-02.SpcCoeff.bin
  tms_tropics-02.TauCoeff.bin
  tms_tropics-03.SpcCoeff.bin
  tms_tropics-03.TauCoeff.bin
  tms_tropics-04.SpcCoeff.bin
  tms_tropics-04.TauCoeff.bin
  tms_tropics-05.SpcCoeff.bin
  tms_tropics-05.TauCoeff.bin
  tms_tropics-06.SpcCoeff.bin
  tms_tropics-06.TauCoeff.bin
  tms_tropics-07.SpcCoeff.bin
  tms_tropics-07.TauCoeff.bin
  tropics_designed_v1.SpcCoeff.bin
  tropics_designed_v1.TauCoeff.bin
  u.omps-npAllFOV_j2.SpcCoeff.bin
  u.omps-npAllFOV_j2.TauCoeff.bin
  u.omps-npAllFOV_n21.SpcCoeff.bin
  u.omps-npAllFOV_n21.TauCoeff.bin
  u.omps-tcAllFOV_j2.SpcCoeff.bin
  u.omps-tcAllFOV_j2.TauCoeff.bin
  u.omps-tcAllFOV_n21.SpcCoeff.bin
  u.omps-tcAllFOV_n21.TauCoeff.bin
  USGS.IRland.EmisCoeff.bin
  USGS.VISland.EmisCoeff.bin
  v.abi_g16.SpcCoeff.bin
  v.abi_g16.TauCoeff.bin
  v.abi_g17.SpcCoeff.bin
  v.abi_g17.TauCoeff.bin
  v.abi_g18.SpcCoeff.bin
  v.abi_gr.SpcCoeff.bin
  v.abi_gr.TauCoeff.bin
  v.ahi_himawari8.SpcCoeff.bin
  v.ahi_himawari8.TauCoeff.bin
  v.ahi_himawari9.SpcCoeff.bin
  v.ahi_himawari9.TauCoeff.bin
  vas_g04.SpcCoeff.bin
  vas_g04.TauCoeff.bin
  vas_g05.SpcCoeff.bin
  vas_g05.TauCoeff.bin
  vas_g06.SpcCoeff.bin
  vas_g06.TauCoeff.bin
  vas_g07.SpcCoeff.bin
  vas_g07.TauCoeff.bin
  v.aster_terra.SpcCoeff.bin
  v.aster_terra.TauCoeff.bin
  v.avhrr2_n14.SpcCoeff.bin
  v.avhrr3_metop-a.SpcCoeff.bin
  v.avhrr3_metop-a.TauCoeff.bin
  v.avhrr3_metop-b.SpcCoeff.bin
  v.avhrr3_metop-b.TauCoeff.bin
  v.avhrr3_n15.SpcCoeff.bin
  v.avhrr3_n15.TauCoeff.bin
  v.avhrr3_n16.SpcCoeff.bin
  v.avhrr3_n16.TauCoeff.bin
  v.avhrr3_n17.SpcCoeff.bin
  v.avhrr3_n17.TauCoeff.bin
  v.avhrr3_n18.SpcCoeff.bin
  v.avhrr3_n18.TauCoeff.bin
  v.avhrr3_n19.SpcCoeff.bin
  v.avhrr3_n19.TauCoeff.bin
  vhrr_kalpana1.SpcCoeff.bin
  vhrr_kalpana1.TauCoeff.bin
  viirs-iD01_j1.SpcCoeff.bin
  viirs-iD01_j1.TauCoeff.bin
  viirs-iD01_npp.SpcCoeff.bin
  viirs-iD01_npp.TauCoeff.bin
  viirs-iD02_j1.SpcCoeff.bin
  viirs-iD02_j1.TauCoeff.bin
  viirs-iD02_npp.SpcCoeff.bin
  viirs-iD02_npp.TauCoeff.bin
  viirs-iD03_j1.SpcCoeff.bin
  viirs-iD03_j1.TauCoeff.bin
  viirs-iD03_npp.SpcCoeff.bin
  viirs-iD03_npp.TauCoeff.bin
  viirs-iD04_j1.SpcCoeff.bin
  viirs-iD04_j1.TauCoeff.bin
  viirs-iD04_npp.SpcCoeff.bin
  viirs-iD04_npp.TauCoeff.bin
  viirs-iD05_j1.SpcCoeff.bin
  viirs-iD05_j1.TauCoeff.bin
  viirs-iD05_npp.SpcCoeff.bin
  viirs-iD05_npp.TauCoeff.bin
  viirs-iD06_j1.SpcCoeff.bin
  viirs-iD06_j1.TauCoeff.bin
  viirs-iD06_npp.SpcCoeff.bin
  viirs-iD06_npp.TauCoeff.bin
  viirs-iD07_j1.SpcCoeff.bin
  viirs-iD07_j1.TauCoeff.bin
  viirs-iD07_npp.SpcCoeff.bin
  viirs-iD07_npp.TauCoeff.bin
  viirs-iD08_j1.SpcCoeff.bin
  viirs-iD08_j1.TauCoeff.bin
  viirs-iD08_npp.SpcCoeff.bin
  viirs-iD08_npp.TauCoeff.bin
  viirs-iD09_j1.SpcCoeff.bin
  viirs-iD09_j1.TauCoeff.bin
  viirs-iD09_npp.SpcCoeff.bin
  viirs-iD09_npp.TauCoeff.bin
  viirs-iD10_j1.SpcCoeff.bin
  viirs-iD10_j1.TauCoeff.bin
  viirs-iD10_npp.SpcCoeff.bin
  viirs-iD10_npp.TauCoeff.bin
  viirs-iD11_j1.SpcCoeff.bin
  viirs-iD11_j1.TauCoeff.bin
  viirs-iD11_npp.SpcCoeff.bin
  viirs-iD11_npp.TauCoeff.bin
  viirs-iD12_j1.SpcCoeff.bin
  viirs-iD12_j1.TauCoeff.bin
  viirs-iD12_npp.SpcCoeff.bin
  viirs-iD12_npp.TauCoeff.bin
  viirs-iD13_j1.SpcCoeff.bin
  viirs-iD13_j1.TauCoeff.bin
  viirs-iD13_npp.SpcCoeff.bin
  viirs-iD13_npp.TauCoeff.bin
  viirs-iD14_j1.SpcCoeff.bin
  viirs-iD14_j1.TauCoeff.bin
  viirs-iD14_npp.SpcCoeff.bin
  viirs-iD14_npp.TauCoeff.bin
  viirs-iD15_j1.SpcCoeff.bin
  viirs-iD15_j1.TauCoeff.bin
  viirs-iD15_npp.SpcCoeff.bin
  viirs-iD15_npp.TauCoeff.bin
  viirs-iD16_j1.SpcCoeff.bin
  viirs-iD16_j1.TauCoeff.bin
  viirs-iD16_npp.SpcCoeff.bin
  viirs-iD16_npp.TauCoeff.bin
  viirs-iD17_j1.SpcCoeff.bin
  viirs-iD17_j1.TauCoeff.bin
  viirs-iD17_npp.SpcCoeff.bin
  viirs-iD17_npp.TauCoeff.bin
  viirs-iD18_j1.SpcCoeff.bin
  viirs-iD18_j1.TauCoeff.bin
  viirs-iD18_npp.SpcCoeff.bin
  viirs-iD18_npp.TauCoeff.bin
  viirs-iD19_j1.SpcCoeff.bin
  viirs-iD19_j1.TauCoeff.bin
  viirs-iD19_npp.SpcCoeff.bin
  viirs-iD19_npp.TauCoeff.bin
  viirs-iD20_j1.SpcCoeff.bin
  viirs-iD20_j1.TauCoeff.bin
  viirs-iD20_npp.SpcCoeff.bin
  viirs-iD20_npp.TauCoeff.bin
  viirs-iD21_j1.SpcCoeff.bin
  viirs-iD21_j1.TauCoeff.bin
  viirs-iD21_npp.SpcCoeff.bin
  viirs-iD21_npp.TauCoeff.bin
  viirs-iD22_j1.SpcCoeff.bin
  viirs-iD22_j1.TauCoeff.bin
  viirs-iD22_npp.SpcCoeff.bin
  viirs-iD22_npp.TauCoeff.bin
  viirs-iD23_j1.SpcCoeff.bin
  viirs-iD23_j1.TauCoeff.bin
  viirs-iD23_npp.SpcCoeff.bin
  viirs-iD23_npp.TauCoeff.bin
  viirs-iD24_j1.SpcCoeff.bin
  viirs-iD24_j1.TauCoeff.bin
  viirs-iD24_npp.SpcCoeff.bin
  viirs-iD24_npp.TauCoeff.bin
  viirs-iD25_j1.SpcCoeff.bin
  viirs-iD25_j1.TauCoeff.bin
  viirs-iD25_npp.SpcCoeff.bin
  viirs-iD25_npp.TauCoeff.bin
  viirs-iD26_j1.SpcCoeff.bin
  viirs-iD26_j1.TauCoeff.bin
  viirs-iD26_npp.SpcCoeff.bin
  viirs-iD26_npp.TauCoeff.bin
  viirs-iD27_j1.SpcCoeff.bin
  viirs-iD27_j1.TauCoeff.bin
  viirs-iD27_npp.SpcCoeff.bin
  viirs-iD27_npp.TauCoeff.bin
  viirs-iD28_j1.SpcCoeff.bin
  viirs-iD28_j1.TauCoeff.bin
  viirs-iD28_npp.SpcCoeff.bin
  viirs-iD28_npp.TauCoeff.bin
  viirs-iD29_j1.SpcCoeff.bin
  viirs-iD29_j1.TauCoeff.bin
  viirs-iD29_npp.SpcCoeff.bin
  viirs-iD29_npp.TauCoeff.bin
  viirs-iD30_j1.SpcCoeff.bin
  viirs-iD30_j1.TauCoeff.bin
  viirs-iD30_npp.SpcCoeff.bin
  viirs-iD30_npp.TauCoeff.bin
  viirs-iD31_j1.SpcCoeff.bin
  viirs-iD31_j1.TauCoeff.bin
  viirs-iD31_npp.SpcCoeff.bin
  viirs-iD31_npp.TauCoeff.bin
  viirs-iD32_j1.SpcCoeff.bin
  viirs-iD32_j1.TauCoeff.bin
  viirs-iD32_npp.SpcCoeff.bin
  viirs-iD32_npp.TauCoeff.bin
  viirs-i_j1.SpcCoeff.bin
  viirs-i_j1.TauCoeff.bin
  viirs-i_j2.SpcCoeff.bin
  viirs-i_j2.TauCoeff.bin
  viirs-i_n21.SpcCoeff.bin
  viirs-i_n21.SpcCoeff.nc
  viirs-i_n21.TauCoeff.bin
  viirs-i_n21.TauCoeff.nc
  viirs-i_npp.SpcCoeff.bin
  viirs-i_npp.TauCoeff.bin
  viirs-mD01_j1.SpcCoeff.bin
  viirs-mD01_j1.TauCoeff.bin
  viirs-mD01_npp.SpcCoeff.bin
  viirs-mD01_npp.TauCoeff.bin
  viirs-mD02_j1.SpcCoeff.bin
  viirs-mD02_j1.TauCoeff.bin
  viirs-mD02_npp.SpcCoeff.bin
  viirs-mD02_npp.TauCoeff.bin
  viirs-mD03_j1.SpcCoeff.bin
  viirs-mD03_j1.TauCoeff.bin
  viirs-mD03_npp.SpcCoeff.bin
  viirs-mD03_npp.TauCoeff.bin
  viirs-mD04_j1.SpcCoeff.bin
  viirs-mD04_j1.TauCoeff.bin
  viirs-mD04_npp.SpcCoeff.bin
  viirs-mD04_npp.TauCoeff.bin
  viirs-mD05_j1.SpcCoeff.bin
  viirs-mD05_j1.TauCoeff.bin
  viirs-mD05_npp.SpcCoeff.bin
  viirs-mD05_npp.TauCoeff.bin
  viirs-mD06_j1.SpcCoeff.bin
  viirs-mD06_j1.TauCoeff.bin
  viirs-mD06_npp.SpcCoeff.bin
  viirs-mD06_npp.TauCoeff.bin
  viirs-mD07_j1.SpcCoeff.bin
  viirs-mD07_j1.TauCoeff.bin
  viirs-mD07_npp.SpcCoeff.bin
  viirs-mD07_npp.TauCoeff.bin
  viirs-mD08_j1.SpcCoeff.bin
  viirs-mD08_j1.TauCoeff.bin
  viirs-mD08_npp.SpcCoeff.bin
  viirs-mD08_npp.TauCoeff.bin
  viirs-mD09_j1.SpcCoeff.bin
  viirs-mD09_j1.TauCoeff.bin
  viirs-mD09_npp.SpcCoeff.bin
  viirs-mD09_npp.TauCoeff.bin
  viirs-mD10_j1.SpcCoeff.bin
  viirs-mD10_j1.TauCoeff.bin
  viirs-mD10_npp.SpcCoeff.bin
  viirs-mD10_npp.TauCoeff.bin
  viirs-mD11_j1.SpcCoeff.bin
  viirs-mD11_j1.TauCoeff.bin
  viirs-mD11_npp.SpcCoeff.bin
  viirs-mD11_npp.TauCoeff.bin
  viirs-mD12_j1.SpcCoeff.bin
  viirs-mD12_j1.TauCoeff.bin
  viirs-mD12_npp.SpcCoeff.bin
  viirs-mD12_npp.TauCoeff.bin
  viirs-mD13_j1.SpcCoeff.bin
  viirs-mD13_j1.TauCoeff.bin
  viirs-mD13_npp.SpcCoeff.bin
  viirs-mD13_npp.TauCoeff.bin
  viirs-mD14_j1.SpcCoeff.bin
  viirs-mD14_j1.TauCoeff.bin
  viirs-mD14_npp.SpcCoeff.bin
  viirs-mD14_npp.TauCoeff.bin
  viirs-mD15_j1.SpcCoeff.bin
  viirs-mD15_j1.TauCoeff.bin
  viirs-mD15_npp.SpcCoeff.bin
  viirs-mD15_npp.TauCoeff.bin
  viirs-mD16_j1.SpcCoeff.bin
  viirs-mD16_j1.TauCoeff.bin
  viirs-mD16_npp.SpcCoeff.bin
  viirs-mD16_npp.TauCoeff.bin
  viirs-m_j1.SpcCoeff.bin
  viirs-m_j1.TauCoeff.bin
  viirs-m_j2.SpcCoeff.bin
  viirs-m_j2.TauCoeff.bin
  viirs-m_n21.SpcCoeff.bin
  viirs-m_n21.SpcCoeff.nc
  viirs-m_n21.TauCoeff.bin
  viirs-m_n21.TauCoeff.nc
  viirs-m_npp.SpcCoeff.bin
  viirs-m_npp.TauCoeff.bin
  v.imgrD1_g11.SpcCoeff.bin
  v.imgrD1_g11.TauCoeff.bin
  v.imgrD1_g12.SpcCoeff.bin
  v.imgrD1_g12.TauCoeff.bin
  v.imgrD1_g13.SpcCoeff.bin
  v.imgrD1_g13.TauCoeff.bin
  v.imgrD1_g14.SpcCoeff.bin
  v.imgrD1_g14.TauCoeff.bin
  v.imgrD1_g15.SpcCoeff.bin
  v.imgrD1_g15.TauCoeff.bin
  v.imgrD1_mt2.SpcCoeff.bin
  v.imgrD1_mt2.TauCoeff.bin
  v.imgrD2_g11.SpcCoeff.bin
  v.imgrD2_g11.TauCoeff.bin
  v.imgrD2_g12.SpcCoeff.bin
  v.imgrD2_g12.TauCoeff.bin
  v.imgrD2_g13.SpcCoeff.bin
  v.imgrD2_g13.TauCoeff.bin
  v.imgrD2_g14.SpcCoeff.bin
  v.imgrD2_g14.TauCoeff.bin
  v.imgrD2_g15.SpcCoeff.bin
  v.imgrD2_g15.TauCoeff.bin
  v.imgrD3_g11.SpcCoeff.bin
  v.imgrD3_g11.TauCoeff.bin
  v.imgrD3_g12.SpcCoeff.bin
  v.imgrD3_g12.TauCoeff.bin
  v.imgrD3_g13.SpcCoeff.bin
  v.imgrD3_g13.TauCoeff.bin
  v.imgrD3_g14.SpcCoeff.bin
  v.imgrD3_g14.TauCoeff.bin
  v.imgrD3_g15.SpcCoeff.bin
  v.imgrD3_g15.TauCoeff.bin
  v.imgrD4_g11.SpcCoeff.bin
  v.imgrD4_g11.TauCoeff.bin
  v.imgrD4_g12.SpcCoeff.bin
  v.imgrD4_g12.TauCoeff.bin
  v.imgrD4_g13.SpcCoeff.bin
  v.imgrD4_g13.TauCoeff.bin
  v.imgrD4_g14.SpcCoeff.bin
  v.imgrD4_g14.TauCoeff.bin
  v.imgrD4_g15.SpcCoeff.bin
  v.imgrD4_g15.TauCoeff.bin
  v.imgrD5_g11.SpcCoeff.bin
  v.imgrD5_g11.TauCoeff.bin
  v.imgrD5_g12.SpcCoeff.bin
  v.imgrD5_g12.TauCoeff.bin
  v.imgrD5_g13.SpcCoeff.bin
  v.imgrD5_g13.TauCoeff.bin
  v.imgrD5_g14.SpcCoeff.bin
  v.imgrD5_g14.TauCoeff.bin
  v.imgrD5_g15.SpcCoeff.bin
  v.imgrD5_g15.TauCoeff.bin
  v.imgrD6_g11.SpcCoeff.bin
  v.imgrD6_g11.TauCoeff.bin
  v.imgrD6_g12.SpcCoeff.bin
  v.imgrD6_g12.TauCoeff.bin
  v.imgrD6_g13.SpcCoeff.bin
  v.imgrD6_g13.TauCoeff.bin
  v.imgrD6_g14.SpcCoeff.bin
  v.imgrD6_g14.TauCoeff.bin
  v.imgrD6_g15.SpcCoeff.bin
  v.imgrD6_g15.TauCoeff.bin
  v.imgrD7_g11.SpcCoeff.bin
  v.imgrD7_g11.TauCoeff.bin
  v.imgrD7_g12.SpcCoeff.bin
  v.imgrD7_g12.TauCoeff.bin
  v.imgrD7_g13.SpcCoeff.bin
  v.imgrD7_g13.TauCoeff.bin
  v.imgrD7_g14.SpcCoeff.bin
  v.imgrD7_g14.TauCoeff.bin
  v.imgrD7_g15.SpcCoeff.bin
  v.imgrD7_g15.TauCoeff.bin
  v.imgrD8_g11.SpcCoeff.bin
  v.imgrD8_g11.TauCoeff.bin
  v.imgrD8_g12.SpcCoeff.bin
  v.imgrD8_g12.TauCoeff.bin
  v.imgrD8_g13.SpcCoeff.bin
  v.imgrD8_g13.TauCoeff.bin
  v.imgrD8_g14.SpcCoeff.bin
  v.imgrD8_g14.TauCoeff.bin
  v.imgrD8_g15.SpcCoeff.bin
  v.imgrD8_g15.TauCoeff.bin
  v.imgr_g11.SpcCoeff.bin
  v.imgr_g11.TauCoeff.bin
  v.imgr_g12.SpcCoeff.bin
  v.imgr_g12.TauCoeff.bin
  v.imgr_g13.SpcCoeff.bin
  v.imgr_g13.TauCoeff.bin
  v.imgr_g14.SpcCoeff.bin
  v.imgr_g14.TauCoeff.bin
  v.imgr_g15.SpcCoeff.bin
  v.imgr_g15.TauCoeff.bin
  v.imgr_mt2.SpcCoeff.bin
  v.imgr_mt2.TauCoeff.bin
  v.iras_fy3a.SpcCoeff.bin
  v.iras_fy3a.TauCoeff.bin
  v.iras_fy3b.SpcCoeff.bin
  v.iras_fy3b.TauCoeff.bin
  virr_fy3a.SpcCoeff.bin
  virr_fy3a.TauCoeff.bin
  vissrDetA_gms5.SpcCoeff.bin
  vissrDetA_gms5.TauCoeff.bin
  vissrDetB_gms5.SpcCoeff.bin
  vissrDetB_gms5.TauCoeff.bin
  v.ivissr_fy2c.SpcCoeff.bin
  v.ivissr_fy2d.SpcCoeff.bin
  v.ivissr_fy2e.SpcCoeff.bin
  v.ivissr_fy2f.SpcCoeff.bin
  v.metimage_metop-sg-a1.SpcCoeff.bin
  v.mi-l_coms.SpcCoeff.bin
  v.mi-l_coms.TauCoeff.bin
  v.mi-lD01_coms.SpcCoeff.bin
  v.mi-lD01_coms.TauCoeff.bin
  v.mi-lD02_coms.SpcCoeff.bin
  v.mi-lD02_coms.TauCoeff.bin
  v.mi-lD03_coms.SpcCoeff.bin
  v.mi-lD03_coms.TauCoeff.bin
  v.mi-lD04_coms.SpcCoeff.bin
  v.mi-lD04_coms.TauCoeff.bin
  v.mi-lD05_coms.SpcCoeff.bin
  v.mi-lD05_coms.TauCoeff.bin
  v.mi-lD06_coms.SpcCoeff.bin
  v.mi-lD06_coms.TauCoeff.bin
  v.mi-lD07_coms.SpcCoeff.bin
  v.mi-lD07_coms.TauCoeff.bin
  v.mi-lD08_coms.SpcCoeff.bin
  v.mi-lD08_coms.TauCoeff.bin
  v.mi-m_coms.SpcCoeff.bin
  v.mi-m_coms.TauCoeff.bin
  v.mi-mD01_coms.SpcCoeff.bin
  v.mi-mD01_coms.TauCoeff.bin
  v.mi-mD02_coms.SpcCoeff.bin
  v.mi-mD02_coms.TauCoeff.bin
  v.mi-mD03_coms.SpcCoeff.bin
  v.mi-mD03_coms.TauCoeff.bin
  v.mi-mD04_coms.SpcCoeff.bin
  v.mi-mD04_coms.TauCoeff.bin
  v.mi-mD05_coms.SpcCoeff.bin
  v.mi-mD05_coms.TauCoeff.bin
  v.mi-mD06_coms.SpcCoeff.bin
  v.mi-mD06_coms.TauCoeff.bin
  v.mi-mD07_coms.SpcCoeff.bin
  v.mi-mD07_coms.TauCoeff.bin
  v.mi-mD08_coms.SpcCoeff.bin
  v.mi-mD08_coms.TauCoeff.bin
  v.modis_aqua.SpcCoeff.bin
  v.modis_aqua.TauCoeff.bin
  v.modisD01_aqua.SpcCoeff.bin
  v.modisD01_aqua.TauCoeff.bin
  v.modisD01_terra.SpcCoeff.bin
  v.modisD01_terra.TauCoeff.bin
  v.modisD02_aqua.SpcCoeff.bin
  v.modisD02_aqua.TauCoeff.bin
  v.modisD02_terra.SpcCoeff.bin
  v.modisD02_terra.TauCoeff.bin
  v.modisD03_aqua.SpcCoeff.bin
  v.modisD03_aqua.TauCoeff.bin
  v.modisD03_terra.SpcCoeff.bin
  v.modisD03_terra.TauCoeff.bin
  v.modisD04_aqua.SpcCoeff.bin
  v.modisD04_aqua.TauCoeff.bin
  v.modisD04_terra.SpcCoeff.bin
  v.modisD04_terra.TauCoeff.bin
  v.modisD05_aqua.SpcCoeff.bin
  v.modisD05_aqua.TauCoeff.bin
  v.modisD05_terra.SpcCoeff.bin
  v.modisD05_terra.TauCoeff.bin
  v.modisD06_aqua.SpcCoeff.bin
  v.modisD06_aqua.TauCoeff.bin
  v.modisD06_terra.SpcCoeff.bin
  v.modisD06_terra.TauCoeff.bin
  v.modisD07_aqua.SpcCoeff.bin
  v.modisD07_aqua.TauCoeff.bin
  v.modisD07_terra.SpcCoeff.bin
  v.modisD07_terra.TauCoeff.bin
  v.modisD08_aqua.SpcCoeff.bin
  v.modisD08_aqua.TauCoeff.bin
  v.modisD08_terra.SpcCoeff.bin
  v.modisD08_terra.TauCoeff.bin
  v.modisD09_aqua.SpcCoeff.bin
  v.modisD09_aqua.TauCoeff.bin
  v.modisD09_terra.SpcCoeff.bin
  v.modisD09_terra.TauCoeff.bin
  v.modisD10_aqua.SpcCoeff.bin
  v.modisD10_aqua.TauCoeff.bin
  v.modisD10_terra.SpcCoeff.bin
  v.modisD10_terra.TauCoeff.bin
  v.modis_terra.SpcCoeff.bin
  v.modis_terra.TauCoeff.bin
  v.seviri_m08.SpcCoeff.bin
  v.seviri_m08.TauCoeff.bin
  v.seviri_m09.SpcCoeff.bin
  v.seviri_m09.TauCoeff.bin
  v.seviri_m10.SpcCoeff.bin
  v.seviri_m10.TauCoeff.bin
  v.sndrD1_g08.SpcCoeff.bin
  v.sndrD1_g08.TauCoeff.bin
  v.sndrD1_g09.SpcCoeff.bin
  v.sndrD1_g09.TauCoeff.bin
  v.sndrD1_g10.SpcCoeff.bin
  v.sndrD1_g10.TauCoeff.bin
  v.sndrD1_g11.SpcCoeff.bin
  v.sndrD1_g11.TauCoeff.bin
  v.sndrD1_g12.SpcCoeff.bin
  v.sndrD1_g12.TauCoeff.bin
  v.sndrD1_g13.SpcCoeff.bin
  v.sndrD1_g13.TauCoeff.bin
  v.sndrD1_g14.SpcCoeff.bin
  v.sndrD1_g14.TauCoeff.bin
  v.sndrD1_g15.SpcCoeff.bin
  v.sndrD1_g15.TauCoeff.bin
  v.sndrD2_g08.SpcCoeff.bin
  v.sndrD2_g08.TauCoeff.bin
  v.sndrD2_g09.SpcCoeff.bin
  v.sndrD2_g09.TauCoeff.bin
  v.sndrD2_g10.SpcCoeff.bin
  v.sndrD2_g10.TauCoeff.bin
  v.sndrD2_g11.SpcCoeff.bin
  v.sndrD2_g11.TauCoeff.bin
  v.sndrD2_g12.SpcCoeff.bin
  v.sndrD2_g12.TauCoeff.bin
  v.sndrD2_g13.SpcCoeff.bin
  v.sndrD2_g13.TauCoeff.bin
  v.sndrD2_g14.SpcCoeff.bin
  v.sndrD2_g14.TauCoeff.bin
  v.sndrD2_g15.SpcCoeff.bin
  v.sndrD2_g15.TauCoeff.bin
  v.sndrD3_g08.SpcCoeff.bin
  v.sndrD3_g08.TauCoeff.bin
  v.sndrD3_g09.SpcCoeff.bin
  v.sndrD3_g09.TauCoeff.bin
  v.sndrD3_g10.SpcCoeff.bin
  v.sndrD3_g10.TauCoeff.bin
  v.sndrD3_g11.SpcCoeff.bin
  v.sndrD3_g11.TauCoeff.bin
  v.sndrD3_g12.SpcCoeff.bin
  v.sndrD3_g12.TauCoeff.bin
  v.sndrD3_g13.SpcCoeff.bin
  v.sndrD3_g13.TauCoeff.bin
  v.sndrD3_g14.SpcCoeff.bin
  v.sndrD3_g14.TauCoeff.bin
  v.sndrD3_g15.SpcCoeff.bin
  v.sndrD3_g15.TauCoeff.bin
  v.sndrD4_g08.SpcCoeff.bin
  v.sndrD4_g08.TauCoeff.bin
  v.sndrD4_g09.SpcCoeff.bin
  v.sndrD4_g09.TauCoeff.bin
  v.sndrD4_g10.SpcCoeff.bin
  v.sndrD4_g10.TauCoeff.bin
  v.sndrD4_g11.SpcCoeff.bin
  v.sndrD4_g11.TauCoeff.bin
  v.sndrD4_g12.SpcCoeff.bin
  v.sndrD4_g12.TauCoeff.bin
  v.sndrD4_g13.SpcCoeff.bin
  v.sndrD4_g13.TauCoeff.bin
  v.sndrD4_g14.SpcCoeff.bin
  v.sndrD4_g14.TauCoeff.bin
  v.sndrD4_g15.SpcCoeff.bin
  v.sndrD4_g15.TauCoeff.bin
  v.sndr_g08.SpcCoeff.bin
  v.sndr_g08.TauCoeff.bin
  v.sndr_g09.SpcCoeff.bin
  v.sndr_g09.TauCoeff.bin
  v.sndr_g10.SpcCoeff.bin
  v.sndr_g10.TauCoeff.bin
  v.sndr_g11.SpcCoeff.bin
  v.sndr_g11.TauCoeff.bin
  v.sndr_g12.SpcCoeff.bin
  v.sndr_g12.TauCoeff.bin
  v.sndr_g13.SpcCoeff.bin
  v.sndr_g13.TauCoeff.bin
  v.sndr_g14.SpcCoeff.bin
  v.sndr_g14.TauCoeff.bin
  v.sndr_g15.SpcCoeff.bin
  v.sndr_g15.TauCoeff.bin
  vtprS1_itos.SpcCoeff.bin
  vtprS1_itos.TauCoeff.bin
  vtprS2_itos.SpcCoeff.bin
  vtprS2_itos.TauCoeff.bin
  vtprS3_itos.SpcCoeff.bin
  vtprS3_itos.TauCoeff.bin
  vtprS4_itos.SpcCoeff.bin
  vtprS4_itos.TauCoeff.bin
  v.viirs-dnb_j1.SpcCoeff.bin
  v.viirs-dnb_j1.TauCoeff.bin
  v.viirs-iD01_j1.SpcCoeff.bin
  v.viirs-iD01_j1.TauCoeff.bin
  v.viirs-iD01_npp.SpcCoeff.bin
  v.viirs-iD01_npp.TauCoeff.bin
  v.viirs-iD02_j1.SpcCoeff.bin
  v.viirs-iD02_j1.TauCoeff.bin
  v.viirs-iD02_npp.SpcCoeff.bin
  v.viirs-iD02_npp.TauCoeff.bin
  v.viirs-iD03_j1.SpcCoeff.bin
  v.viirs-iD03_j1.TauCoeff.bin
  v.viirs-iD03_npp.SpcCoeff.bin
  v.viirs-iD03_npp.TauCoeff.bin
  v.viirs-iD04_j1.SpcCoeff.bin
  v.viirs-iD04_j1.TauCoeff.bin
  v.viirs-iD04_npp.SpcCoeff.bin
  v.viirs-iD04_npp.TauCoeff.bin
  v.viirs-iD05_j1.SpcCoeff.bin
  v.viirs-iD05_j1.TauCoeff.bin
  v.viirs-iD05_npp.SpcCoeff.bin
  v.viirs-iD05_npp.TauCoeff.bin
  v.viirs-iD06_j1.SpcCoeff.bin
  v.viirs-iD06_j1.TauCoeff.bin
  v.viirs-iD06_npp.SpcCoeff.bin
  v.viirs-iD06_npp.TauCoeff.bin
  v.viirs-iD07_j1.SpcCoeff.bin
  v.viirs-iD07_j1.TauCoeff.bin
  v.viirs-iD07_npp.SpcCoeff.bin
  v.viirs-iD07_npp.TauCoeff.bin
  v.viirs-iD08_j1.SpcCoeff.bin
  v.viirs-iD08_j1.TauCoeff.bin
  v.viirs-iD08_npp.SpcCoeff.bin
  v.viirs-iD08_npp.TauCoeff.bin
  v.viirs-iD09_j1.SpcCoeff.bin
  v.viirs-iD09_j1.TauCoeff.bin
  v.viirs-iD09_npp.SpcCoeff.bin
  v.viirs-iD09_npp.TauCoeff.bin
  v.viirs-iD10_j1.SpcCoeff.bin
  v.viirs-iD10_j1.TauCoeff.bin
  v.viirs-iD10_npp.SpcCoeff.bin
  v.viirs-iD10_npp.TauCoeff.bin
  v.viirs-iD11_j1.SpcCoeff.bin
  v.viirs-iD11_j1.TauCoeff.bin
  v.viirs-iD11_npp.SpcCoeff.bin
  v.viirs-iD11_npp.TauCoeff.bin
  v.viirs-iD12_j1.SpcCoeff.bin
  v.viirs-iD12_j1.TauCoeff.bin
  v.viirs-iD12_npp.SpcCoeff.bin
  v.viirs-iD12_npp.TauCoeff.bin
  v.viirs-iD13_j1.SpcCoeff.bin
  v.viirs-iD13_j1.TauCoeff.bin
  v.viirs-iD13_npp.SpcCoeff.bin
  v.viirs-iD13_npp.TauCoeff.bin
  v.viirs-iD14_j1.SpcCoeff.bin
  v.viirs-iD14_j1.TauCoeff.bin
  v.viirs-iD14_npp.SpcCoeff.bin
  v.viirs-iD14_npp.TauCoeff.bin
  v.viirs-iD15_j1.SpcCoeff.bin
  v.viirs-iD15_j1.TauCoeff.bin
  v.viirs-iD15_npp.SpcCoeff.bin
  v.viirs-iD15_npp.TauCoeff.bin
  v.viirs-iD16_j1.SpcCoeff.bin
  v.viirs-iD16_j1.TauCoeff.bin
  v.viirs-iD16_npp.SpcCoeff.bin
  v.viirs-iD16_npp.TauCoeff.bin
  v.viirs-iD17_j1.SpcCoeff.bin
  v.viirs-iD17_j1.TauCoeff.bin
  v.viirs-iD17_npp.SpcCoeff.bin
  v.viirs-iD17_npp.TauCoeff.bin
  v.viirs-iD18_j1.SpcCoeff.bin
  v.viirs-iD18_j1.TauCoeff.bin
  v.viirs-iD18_npp.SpcCoeff.bin
  v.viirs-iD18_npp.TauCoeff.bin
  v.viirs-iD19_j1.SpcCoeff.bin
  v.viirs-iD19_j1.TauCoeff.bin
  v.viirs-iD19_npp.SpcCoeff.bin
  v.viirs-iD19_npp.TauCoeff.bin
  v.viirs-iD20_j1.SpcCoeff.bin
  v.viirs-iD20_j1.TauCoeff.bin
  v.viirs-iD20_npp.SpcCoeff.bin
  v.viirs-iD20_npp.TauCoeff.bin
  v.viirs-iD21_j1.SpcCoeff.bin
  v.viirs-iD21_j1.TauCoeff.bin
  v.viirs-iD21_npp.SpcCoeff.bin
  v.viirs-iD21_npp.TauCoeff.bin
  v.viirs-iD22_j1.SpcCoeff.bin
  v.viirs-iD22_j1.TauCoeff.bin
  v.viirs-iD22_npp.SpcCoeff.bin
  v.viirs-iD22_npp.TauCoeff.bin
  v.viirs-iD23_j1.SpcCoeff.bin
  v.viirs-iD23_j1.TauCoeff.bin
  v.viirs-iD23_npp.SpcCoeff.bin
  v.viirs-iD23_npp.TauCoeff.bin
  v.viirs-iD24_j1.SpcCoeff.bin
  v.viirs-iD24_j1.TauCoeff.bin
  v.viirs-iD24_npp.SpcCoeff.bin
  v.viirs-iD24_npp.TauCoeff.bin
  v.viirs-iD25_j1.SpcCoeff.bin
  v.viirs-iD25_j1.TauCoeff.bin
  v.viirs-iD25_npp.SpcCoeff.bin
  v.viirs-iD25_npp.TauCoeff.bin
  v.viirs-iD26_j1.SpcCoeff.bin
  v.viirs-iD26_j1.TauCoeff.bin
  v.viirs-iD26_npp.SpcCoeff.bin
  v.viirs-iD26_npp.TauCoeff.bin
  v.viirs-iD27_j1.SpcCoeff.bin
  v.viirs-iD27_j1.TauCoeff.bin
  v.viirs-iD27_npp.SpcCoeff.bin
  v.viirs-iD27_npp.TauCoeff.bin
  v.viirs-iD28_j1.SpcCoeff.bin
  v.viirs-iD28_j1.TauCoeff.bin
  v.viirs-iD28_npp.SpcCoeff.bin
  v.viirs-iD28_npp.TauCoeff.bin
  v.viirs-iD29_j1.SpcCoeff.bin
  v.viirs-iD29_j1.TauCoeff.bin
  v.viirs-iD29_npp.SpcCoeff.bin
  v.viirs-iD29_npp.TauCoeff.bin
  v.viirs-iD30_j1.SpcCoeff.bin
  v.viirs-iD30_j1.TauCoeff.bin
  v.viirs-iD30_npp.SpcCoeff.bin
  v.viirs-iD30_npp.TauCoeff.bin
  v.viirs-iD31_j1.SpcCoeff.bin
  v.viirs-iD31_j1.TauCoeff.bin
  v.viirs-iD31_npp.SpcCoeff.bin
  v.viirs-iD31_npp.TauCoeff.bin
  v.viirs-iD32_j1.SpcCoeff.bin
  v.viirs-iD32_j1.TauCoeff.bin
  v.viirs-iD32_npp.SpcCoeff.bin
  v.viirs-iD32_npp.TauCoeff.bin
  v.viirs-i_j1.SpcCoeff.bin
  v.viirs-i_j1.TauCoeff.bin
  v.viirs-i_j2.SpcCoeff.bin
  v.viirs-i_j2.SpcCoeff.nc
  v.viirs-i_j2.TauCoeff.bin
  v.viirs-i_j2.TauCoeff.nc
  v.viirs-i_n21.SpcCoeff.bin
  v.viirs-i_n21.SpcCoeff.nc
  v.viirs-i_n21.TauCoeff.bin
  v.viirs-i_n21.TauCoeff.nc
  v.viirs-i_npp.SpcCoeff.bin
  v.viirs-i_npp.TauCoeff.bin
  v.viirs-mD01_j1.SpcCoeff.bin
  v.viirs-mD01_j1.TauCoeff.bin
  v.viirs-mD01_npp.SpcCoeff.bin
  v.viirs-mD01_npp.TauCoeff.bin
  v.viirs-mD02_j1.SpcCoeff.bin
  v.viirs-mD02_j1.TauCoeff.bin
  v.viirs-mD02_npp.SpcCoeff.bin
  v.viirs-mD02_npp.TauCoeff.bin
  v.viirs-mD03_j1.SpcCoeff.bin
  v.viirs-mD03_j1.TauCoeff.bin
  v.viirs-mD03_npp.SpcCoeff.bin
  v.viirs-mD03_npp.TauCoeff.bin
  v.viirs-mD04_j1.SpcCoeff.bin
  v.viirs-mD04_j1.TauCoeff.bin
  v.viirs-mD04_npp.SpcCoeff.bin
  v.viirs-mD04_npp.TauCoeff.bin
  v.viirs-mD05_j1.SpcCoeff.bin
  v.viirs-mD05_j1.TauCoeff.bin
  v.viirs-mD05_npp.SpcCoeff.bin
  v.viirs-mD05_npp.TauCoeff.bin
  v.viirs-mD06_j1.SpcCoeff.bin
  v.viirs-mD06_j1.TauCoeff.bin
  v.viirs-mD06_npp.SpcCoeff.bin
  v.viirs-mD06_npp.TauCoeff.bin
  v.viirs-mD07_j1.SpcCoeff.bin
  v.viirs-mD07_j1.TauCoeff.bin
  v.viirs-mD07_npp.SpcCoeff.bin
  v.viirs-mD07_npp.TauCoeff.bin
  v.viirs-mD08_j1.SpcCoeff.bin
  v.viirs-mD08_j1.TauCoeff.bin
  v.viirs-mD08_npp.SpcCoeff.bin
  v.viirs-mD08_npp.TauCoeff.bin
  v.viirs-mD09_j1.SpcCoeff.bin
  v.viirs-mD09_j1.TauCoeff.bin
  v.viirs-mD09_npp.SpcCoeff.bin
  v.viirs-mD09_npp.TauCoeff.bin
  v.viirs-mD10_j1.SpcCoeff.bin
  v.viirs-mD10_j1.TauCoeff.bin
  v.viirs-mD10_npp.SpcCoeff.bin
  v.viirs-mD10_npp.TauCoeff.bin
  v.viirs-mD11_j1.SpcCoeff.bin
  v.viirs-mD11_j1.TauCoeff.bin
  v.viirs-mD11_npp.SpcCoeff.bin
  v.viirs-mD11_npp.TauCoeff.bin
  v.viirs-mD12_j1.SpcCoeff.bin
  v.viirs-mD12_j1.TauCoeff.bin
  v.viirs-mD12_npp.SpcCoeff.bin
  v.viirs-mD12_npp.TauCoeff.bin
  v.viirs-mD13_j1.SpcCoeff.bin
  v.viirs-mD13_j1.TauCoeff.bin
  v.viirs-mD13_npp.SpcCoeff.bin
  v.viirs-mD13_npp.TauCoeff.bin
  v.viirs-mD14_j1.SpcCoeff.bin
  v.viirs-mD14_j1.TauCoeff.bin
  v.viirs-mD14_npp.SpcCoeff.bin
  v.viirs-mD14_npp.TauCoeff.bin
  v.viirs-mD15_j1.SpcCoeff.bin
  v.viirs-mD15_j1.TauCoeff.bin
  v.viirs-mD15_npp.SpcCoeff.bin
  v.viirs-mD15_npp.TauCoeff.bin
  v.viirs-mD16_j1.SpcCoeff.bin
  v.viirs-mD16_j1.TauCoeff.bin
  v.viirs-mD16_npp.SpcCoeff.bin
  v.viirs-mD16_npp.TauCoeff.bin
  v.viirs-m_j1.SpcCoeff.bin
  v.viirs-m_j1.TauCoeff.bin
  v.viirs-m_j2.SpcCoeff.bin
  v.viirs-m_j2.SpcCoeff.nc
  v.viirs-m_j2.TauCoeff.bin
  v.viirs-m_j2.TauCoeff.nc
  v.viirs-m_n21.SpcCoeff.bin
  v.viirs-m_n21.SpcCoeff.nc
  v.viirs-m_n21.TauCoeff.bin
  v.viirs-m_n21.TauCoeff.nc
  v.viirs-m_npp.SpcCoeff.bin
  v.viirs-m_npp.TauCoeff.bin
  windsat_coriolis.SpcCoeff.bin
  windsat_coriolis.TauCoeff.bin
  WuSmith.IRwater.EmisCoeff.bin
  zssmis_f16.TauCoeff.bin
  zssmis_f17.TauCoeff.bin
  zssmis_f18.TauCoeff.bin
  zssmis_f19.TauCoeff.bin
  zssmis_f20.TauCoeff.bin
)
